In [ ]:
import numpy as np

In [2]:
gym_data = np.array([
  [28, 75, 175, 4],
  [34, 68, 168, 3],
  [45, 82, 180, 2],
  [22, 58, 162, 5],
  [38, 90, 0, 1],
  [29, 65, 170, 0]
])

# print(gym_data)
# sotoone 0 sen  SAL
# sotoone 1 vazn KG
# sotoone 2 ghad CM
# sotoone 3 tedad jalasate hafte
member_names = np.array(["Ali", "Sara", "Reza", "Neda", "Hassan", "Maryam"])

gym_data_zero_filled = np.where(gym_data == 0, np.mean(gym_data, axis=0).astype(int), gym_data)
print(f"gym data zero filled:\n"
      f"{gym_data_zero_filled}\n"
      f"gym data shape: {gym_data.shape}")

gym data zero filled:
[[ 28  75 175   4]
 [ 34  68 168   3]
 [ 45  82 180   2]
 [ 22  58 162   5]
 [ 38  90 142   1]
 [ 29  65 170   2]]
gym data shape: (6, 4)


# 2

In [3]:
weights = gym_data_zero_filled[:, 1].copy()
heights = gym_data_zero_filled[:, 2].copy()
train_of_week = gym_data_zero_filled[:, 3].copy()

# 3

In [4]:
bmi = weights / ((heights / 100) ** 2)
score = bmi + (2 * train_of_week)
print(score)

final_data = np.hstack((gym_data_zero_filled, score.reshape(-1, 1)))
print(final_data)

[32.48979592 30.09297052 29.30864198 32.10028959 46.63400119 26.49134948]
[[ 28.          75.         175.           4.          32.48979592]
 [ 34.          68.         168.           3.          30.09297052]
 [ 45.          82.         180.           2.          29.30864198]
 [ 22.          58.         162.           5.          32.10028959]
 [ 38.          90.         142.           1.          46.63400119]
 [ 29.          65.         170.           2.          26.49134948]]


# 4

In [5]:
max_index = np.argmax(final_data[:, 4])
max_name = member_names[max_index]
max_score = np.max(final_data[:, 4])
print(f"max score name: {max_name}, max Score: {max_score}")

mean_train = np.mean(train_of_week)
std_train = np.std(train_of_week)
z_score = np.abs((train_of_week - mean_train) / std_train)

max score name: Hassan, max Score: 46.634001190240035


# 5

In [6]:
max_diff_index_std = np.argmax(z_score)
max_diff_name_std = member_names[max_diff_index_std]
max_diff_train_of_week_std = train_of_week[max_diff_index_std]

print(f"max difference name std: {max_diff_name_std}, train of week std: {max_diff_train_of_week_std}")

max difference name std: Neda, train of week std: 5
