In [1]:
import numpy as np

In [2]:
#quiz, mian, final
scores = np.array([
  [18, 15, 20],
  [12, 14, 16],
  [20, 19, 18],
  [10, 8, 15]
])
scheme_A = np.array([0.5, 0.3, 0.2])
scheme_B = np.array([0.2, 0.3, 0.5])
scheme_C = np.array([0.1, 0.2, 0.7])

# 1

In [3]:
weight_matrix = np.array([scheme_A, scheme_B, scheme_C])
print(f"weight_matrix: \n{weight_matrix}")

weight_matrix: 
[[0.5 0.3 0.2]
 [0.2 0.3 0.5]
 [0.1 0.2 0.7]]


# 2

In [4]:
final_scores = scores @ weight_matrix.T
print(f"final_scores: \n{final_scores}")
print(f"final_scores shape: \n{final_scores.shape}")

final_scores: 
[[17.5 18.1 18.8]
 [13.4 14.6 15.2]
 [19.3 18.7 18.4]
 [10.4 11.9 13.1]]
final_scores shape: 
(4, 3)


# 3

In [5]:
arg_max = np.argmax(final_scores, axis=1)
labels = ['A', 'B', 'C']
for i, j in enumerate(arg_max):
  print(f"{i}: {labels[j]}")


0: C
1: C
2: A
3: C


# 4

In [6]:
means = np.mean(final_scores, axis=0)
print(f"means:\n{means}")
max_mean = np.max(means)
max_arg = np.argmax(means)
print(f"max_arg: {max_arg}\nmax_mean: {max_mean}")

means:
[15.15  15.825 16.375]
max_arg: 2
max_mean: 16.375


# 5

In [7]:
# w1 + w2 + w3 = 1
# w3 = 2 * w1

quiz_weight = 0.25
final_weight = 2 * quiz_weight
midterm_weight = 1 - (quiz_weight + final_weight)

scheme_D = np.array((quiz_weight, midterm_weight, final_weight))

print(f"scheme_D: \n{scheme_D}")
weight_matrix = np.vstack((weight_matrix, scheme_D))
print(f"weight_matrix: \n{weight_matrix}")

scheme_D: 
[0.25 0.25 0.5 ]
weight_matrix: 
[[0.5  0.3  0.2 ]
 [0.2  0.3  0.5 ]
 [0.1  0.2  0.7 ]
 [0.25 0.25 0.5 ]]
