In [1]:
import numpy as np

In [2]:
importance = np.array([3, 8, 1, 9, 4, 7])
# print(importance.shape)

importance_reshaped1 = importance.reshape(-1, 1)
print(f"importance_reshaped1.shape: {importance_reshaped1.shape}")
print(f"importance_reshaped1: \n{importance_reshaped1}")

importance_reshaped2 = np.expand_dims(importance, axis=1)
print(f"importance_reshaped2.shape: {importance_reshaped2.shape}")
print(f"importance_reshaped2: \n{importance_reshaped2}")

importance_reshaped3 = importance[:, np.newaxis]
print(f"importance_reshaped3.shape: {importance_reshaped3.shape}")
print(f"importance_reshaped3: \n{importance_reshaped3}")



importance_reshaped1.shape: (6, 1)
importance_reshaped1: 
[[3]
 [8]
 [1]
 [9]
 [4]
 [7]]
importance_reshaped2.shape: (6, 1)
importance_reshaped2: 
[[3]
 [8]
 [1]
 [9]
 [4]
 [7]]
importance_reshaped3.shape: (6, 1)
importance_reshaped3: 
[[3]
 [8]
 [1]
 [9]
 [4]
 [7]]


# 2

In [3]:
model_out = np.array([[[0.9]]])
print(model_out[0][0][0])
print(model_out.item(0))


0.9
0.9


# 3

In [4]:
notes = np.array([5, 10, 15, 20, 25])
pinned = notes[1:3]
pinned[0] = 999
print(f"without copy: {notes}")

notes = np.array([5, 10, 15, 20, 25])
pinned = notes[1:3].copy()
pinned[0] = 999
print(f"with copy {notes}")

without copy: [  5 999  15  20  25]
with copy [ 5 10 15 20 25]


# 4

In [5]:
notes = np.array([5, 10, 15, 20, 25])
pinned = notes
pinned[0] = pinned[-1] % pinned[0]
print(f"referenced address: \nnote'{notes}' = pinned'{pinned}'")

referenced address: 
note'[ 0 10 15 20 25]' = pinned'[ 0 10 15 20 25]'
