In [1]:
import numpy as np

In [2]:
def scale_range_data(data):
  min_vals = np.min(data, axis=0)
  max_vals = np.max(data, axis=0)
  return (data - min_vals) / (max_vals - min_vals)


# 1

In [3]:
# zamane pokht(min), celery, tondi(1_10), tedade mavade avaliye
recipes = np.array([
  [15, 350, 2, 5],
  [45, 600, 7, 10],
  [10, 200, 0, 3],
  [30, 450, 5, 7],
  [60, 800, 8, 12]
])
recipe_names = ["Salad", "Curry", "Toast", "Pasta", "Stew"]

recipes_scaled = scale_range_data(recipes)
print(recipes_scaled)



[[0.1        0.25       0.25       0.22222222]
 [0.7        0.66666667 0.875      0.77777778]
 [0.         0.         0.         0.        ]
 [0.4        0.41666667 0.625      0.44444444]
 [1.         1.         1.         1.        ]]


# 2

In [4]:
users = np.array([
  [10, 250, 1, 4],
  [50, 700, 8, 11],
  [25, 400, 4, 6]
])

users_scaled = scale_range_data(users)
print(users_scaled)


[[0.         0.         0.         0.        ]
 [1.         1.         1.         1.        ]
 [0.375      0.33333333 0.42857143 0.28571429]]


# 3

In [5]:
distances = np.sqrt(np.sum((users_scaled[:, np.newaxis, :] - recipes_scaled[np.newaxis, :, :]) ** 2, axis=2))

print(f"distances: \n{distances}")


distances: 
[[0.42939809 1.51822519 0.         0.96008696 2.        ]
 [1.59371838 0.51586706 2.         1.07216825 0.        ]
 [0.3442215  0.81127126 0.71905649 0.26711213 1.29298265]]


# 4

In [6]:
for i in range(len(users)):
  sorted_indices = np.argsort(distances[i])
  sorted_recipes = np.take(recipe_names, sorted_indices)
  sorted_distances = distances[i][sorted_indices]

  print(f"\nuser {i + 1}:")
  print(f"  rank {sorted_recipes[0]}: {sorted_recipes[0]} (dist = {sorted_distances[0]:.4f})")



user 1:
  rank Toast: Toast (dist = 0.0000)

user 2:
  rank Stew: Stew (dist = 0.0000)

user 3:
  rank Pasta: Pasta (dist = 0.2671)


# 5

In [7]:
for i in range(len(users)):
  sorted_indices = np.argsort(distances[i])
  sorted_recipes = np.take(recipe_names, sorted_indices)
  sorted_distances = distances[i][sorted_indices]

  print(f"\nuser {i + 1}:")
  for rank, (recipe, dist) in enumerate(zip(sorted_recipes, sorted_distances), 1):
    print(f"  rank {rank}: {recipe} (dist = {dist:.4f})")


user 1:
  rank 1: Toast (dist = 0.0000)
  rank 2: Salad (dist = 0.4294)
  rank 3: Pasta (dist = 0.9601)
  rank 4: Curry (dist = 1.5182)
  rank 5: Stew (dist = 2.0000)

user 2:
  rank 1: Stew (dist = 0.0000)
  rank 2: Curry (dist = 0.5159)
  rank 3: Pasta (dist = 1.0722)
  rank 4: Salad (dist = 1.5937)
  rank 5: Toast (dist = 2.0000)

user 3:
  rank 1: Pasta (dist = 0.2671)
  rank 2: Salad (dist = 0.3442)
  rank 3: Toast (dist = 0.7191)
  rank 4: Curry (dist = 0.8113)
  rank 5: Stew (dist = 1.2930)
