In [25]:
import numpy as np

In [36]:
#quiz, mian, final
scores = np.array([
  [18, 15, 20],
  [12, 14, 16],
  [20, 19, 18],
  [10, 8, 15]
])
scheme_A = np.array([0.5, 0.3, 0.2])
scheme_B = np.array([0.2, 0.3, 0.5])
scheme_C = np.array([0.1, 0.2, 0.7])

# 1

In [41]:
weight_matrix = np.array([scheme_A, scheme_B, scheme_C])
print(f"weight_matrix: \n{weight_matrix}")

weight_matrix: 
[[0.5 0.3 0.2]
 [0.2 0.3 0.5]
 [0.1 0.2 0.7]]


In [43]:
final_scores = scores @ weight_matrix
print(f"final_scores: \n{final_scores}")

final_scores: 
[[14.  13.9 25.1]
 [10.4 11.  20.6]
 [15.6 15.3 26.1]
 [ 8.1  8.4 16.5]]
