In [2]:
import numpy as np
from pprint import pprint

In [3]:
bib_numbers = np.array([101, 102, 103, 104, 105, 106])
times_5k = np.array([22.3, 25.1, 21.8, 26.4, 23.0, 24.7])

# 1

In [4]:
bib_numbers_2 = np.array([107, 108])
times_5k_2 = np.array([20.5, 27.9])

bib_numbers = np.hstack((bib_numbers, bib_numbers_2))
times_5k = np.hstack((times_5k, times_5k_2))

backup_bib_numbers = bib_numbers.copy()
backup_times_5k = times_5k.copy()

print(bib_numbers)
print(times_5k)

[101 102 103 104 105 106 107 108]
[22.3 25.1 21.8 26.4 23.  24.7 20.5 27.9]


# 2

In [21]:
np.random.seed(0)
runners = np.column_stack((bib_numbers, times_5k))
np.random.shuffle(runners)
bib_numbers = runners[:, 0]
times_5k = runners[:, 1]
pprint(bib_numbers)
pprint(times_5k)
pprint(backup_bib_numbers)
pprint(backup_times_5k)

array([107., 102., 103., 108., 104., 101., 106., 105.])
array([20.5, 25.1, 21.8, 27.9, 26.4, 22.3, 24.7, 23. ])
array([101, 102, 103, 104, 105, 106, 107, 108])
array([22.3, 25.1, 21.8, 26.4, 23. , 24.7, 20.5, 27.9])


# 3

In [28]:
# print(runners)

sorted_indices = np.argsort(runners[:, 0])

# print(f"sorted_indices {sorted_indices}")

print(f"rank{'':<3} bib{'':<5} time{'':>6}")
for rank, idx in enumerate(sorted_indices, 1):
  bib = bib_numbers[idx]
  time = times_5k[idx]
  print(f"  {rank:<3}  {bib:<5}  {time:>6.1f}")

rank    bib      time      
  1    101.0    22.3
  2    102.0    25.1
  3    103.0    21.8
  4    104.0    26.4
  5    105.0    23.0
  6    106.0    24.7
  7    107.0    20.5
  8    108.0    27.9


# 4

In [35]:
bib = 104
rank = np.where(bib_numbers == bib)[0][0]
time = times_5k[rank]
print(f"rank: {rank:<3} bib: {bib:<5} time: {time:>6}")

rank: 4   bib: 104   time:   26.4
