In [1]:
import numpy as np

In [2]:
# rng = np.random.default_rng(seed=42)

np.random.seed(0)
weather_data = np.random.randn(2, 8, 4) * 5 + 20
weather_data

array([[[28.82026173, 22.00078604, 24.89368992, 31.204466  ],
        [29.33778995, 15.1136106 , 24.75044209, 19.24321396],
        [19.48390574, 22.05299251, 20.72021786, 27.27136753],
        [23.80518863, 20.60837508, 22.21931616, 21.66837164],
        [27.47039537, 18.97420868, 21.56533851, 15.7295213 ],
        [ 7.23505092, 23.26809298, 24.32218099, 16.2891749 ],
        [31.34877312, 12.72817163, 20.22879259, 19.06408075],
        [27.66389607, 27.34679385, 20.77473713, 21.8908126 ]],

       [[15.56107126, 10.09601766, 18.26043925, 20.78174485],
        [26.1514534 , 26.01189924, 18.06336591, 18.48848625],
        [14.75723517, 12.89991031, 11.46864905, 29.75387698],
        [17.45173909, 17.80962849, 13.7360232 , 23.88745178],
        [11.93051076, 18.9362986 , 15.52266719, 21.93451249],
        [17.44597431, 14.09683908, 19.85908886, 22.14165935],
        [20.33258611, 21.51235949, 16.82838953, 18.18629417],
        [16.63769776, 18.20223419, 15.93426859, 11.36858699]]])

In [3]:
def analyze_day(data: np.ndarray) -> bool:
  return data.shape == (4, 8)

# 1

In [4]:
day2 = weather_data[1]
print(f"day2.shape: {day2.shape}")
day2_t = day2.T
print(f"day2_t.shape: {day2_t.shape}")
print(f"analyze_day: {analyze_day(day2_t)}")

day2.shape: (8, 4)
day2_t.shape: (4, 8)
analyze_day: True


# 2

In [5]:
flatten_weather_data = weather_data.flatten()
# flatten_weather_data = weather_data.reshape(-1)
print("flatten_weather_data.shape:", flatten_weather_data.shape)

flatten_weather_data.shape: (64,)


# 3

In [6]:
example_matrix = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

print(f"example_matrix: \n{example_matrix}\n")

flattened = example_matrix.flatten()
print(f"\nflatten(): \n{flattened} \n")

transposed = example_matrix.T
print(f"\ntransposed: \n{transposed} \n")


example_matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


flatten(): 
[1 2 3 4 5 6 7 8 9] 


transposed: 
[[1 4 7]
 [2 5 8]
 [3 6 9]] 



# 4

In [7]:
day3 = np.random.randn(8, 4) * 5 + 20

# weather_data_3days = np.stack([weather_data[0], weather_data[1], day3], axis=0)
weather_data_3days = np.concatenate([weather_data, day3[np.newaxis, :, :]], axis=0)

print(f"weather_data_3days.shape: {weather_data_3days.shape}")
print(f"weather_data_3days: {weather_data_3days}")

weather_data_3days.shape: (3, 8, 4)
weather_data_3days: [[[28.82026173 22.00078604 24.89368992 31.204466  ]
  [29.33778995 15.1136106  24.75044209 19.24321396]
  [19.48390574 22.05299251 20.72021786 27.27136753]
  [23.80518863 20.60837508 22.21931616 21.66837164]
  [27.47039537 18.97420868 21.56533851 15.7295213 ]
  [ 7.23505092 23.26809298 24.32218099 16.2891749 ]
  [31.34877312 12.72817163 20.22879259 19.06408075]
  [27.66389607 27.34679385 20.77473713 21.8908126 ]]

 [[15.56107126 10.09601766 18.26043925 20.78174485]
  [26.1514534  26.01189924 18.06336591 18.48848625]
  [14.75723517 12.89991031 11.46864905 29.75387698]
  [17.45173909 17.80962849 13.7360232  23.88745178]
  [11.93051076 18.9362986  15.52266719 21.93451249]
  [17.44597431 14.09683908 19.85908886 22.14165935]
  [20.33258611 21.51235949 16.82838953 18.18629417]
  [16.63769776 18.20223419 15.93426859 11.36858699]]

 [[20.88713071 17.99109532 11.84900827 22.31391128]
  [15.46350818 20.25972698 23.64545281 20.64491455]
  [2