In [8]:
### Q1

import numpy as np

song = np.array([0.7, 0.9, 0.6])
user_taste = np.array([0.6, 0.8, 0.5])

elementwise = song * user_taste

print(elementwise)
print(np.dot(song, user_taste))

w = np.array([0.6, 0.8, 0.5])
b = 0.3

print(np.dot(song, w) + b)

song1 = np.array([0.9, 0.1])
song2 = np.array([0.85, 0.15])
song3 = np.array([-0.9, -0.1])

def cosine_similarity(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

cosine_similarity_song1_song2 = cosine_similarity(song1, song2)
cosine_similarity_song1_song3 = cosine_similarity(song1, song3)
cosine_similarity_song2_song3 = cosine_similarity(song2, song3)

print(f"cosine_similarity_song1_song2: {cosine_similarity_song1_song2}")
print(f"cosine_similarity_song1_song3: {cosine_similarity_song1_song3}")
print(f"cosine_similarity_song2_song3: {cosine_similarity_song2_song3}")

songs = np.random.rand(5, 3)

# songs = [[-0.52019337, 0.02765299, 0.45786853],
#          [0.54900505, 0.17461988, 0.40596692],
#          [0.93361316, 0.72608967, 0.07674054],
#          [0.21292646, 0.72053582, 0.4500854 ],
#          [0.98442785, 0.46167515, 0.2692847 ],]

# print(songs)

print(np.dot(songs, user_taste) / (np.linalg.norm(songs, axis=1) * np.linalg.norm(user_taste)))



[0.42 0.72 0.3 ]
1.4400000000000002
1.7400000000000002
cosine_similarity_song1_song2: 0.9979517409161514
cosine_similarity_song1_song3: -0.9999999999999999
cosine_similarity_song2_song3: -0.9979517409161514
[0.98583383 0.72297463 0.91082206 0.88881937 0.92844574]


In [9]:
# Q2
import numpy as np
stats=np.random.rand(4,3)

skill_matrix=np.random.rand(3,5)

super_hero = stats@skill_matrix

print(f" super hero matrix:\n{super_hero}\nskill matrix : \n{skill_matrix}\nstats matrix:\n{stats}")

X_chars=np.array([[80,40,60],[30,90,50],[70,70,70],[95,20,40]])

W_skills=np.random.randn(3,3)

W_wrong=np.random.randn(5,3)

b_skills=np.array([1.0,-0.5,0.2])

Z = X_chars @ W_skills + b_skills

Z_wrong = X_chars @ W_wrong.T

print(f"neoruns predicts: \n{Z_wrong.shape}")

 super hero matrix:
[[0.76356531 1.29839448 0.99444711 0.90844404 1.57447385]
 [0.51406659 0.50704825 0.68908298 0.62564915 0.81137996]
 [0.40362976 0.63956016 0.5729241  0.51407429 0.80580949]
 [0.16617762 0.68735568 0.6892154  0.53649744 0.67439087]]
skill matrix : 
[[0.51968901 0.82573888 0.04916523 0.1685071  0.95888458]
 [0.58643541 0.01662772 0.8623686  0.7684112  0.5504945 ]
 [0.07175039 0.93145926 0.8423003  0.62196741 0.78842714]]
stats matrix:
[[0.83987387 0.47935759 0.64083034]
 [0.33672957 0.54931165 0.23604226]
 [0.38186187 0.30795957 0.3426036 ]
 [0.07092252 0.1382268  0.67259388]]
neoruns predicts: 
(4, 5)


In [54]:
# Q3
import numpy as np

np.random.seed(0)
questions = np.array(['Q1', 'Q2', 'Q3', 'Q4', 'Q5'])
answers = np.array(['B', 'D', 'A', 'C', 'B'])
shuffle_indexes = np.random.permutation(len(questions))
questions_shuffled = questions[shuffle_indexes]
answers_shuffled = answers[shuffle_indexes]
print(questions_shuffled)
print(answers_shuffled)

new_questions = np.array(['Q6', 'Q7'])
new_answers = np.array(['A', 'D'])

stacked_question = np.hstack((questions_shuffled, new_questions))

stacked_answers = np.hstack((answers_shuffled, new_answers))

print(f"stacked_question: {stacked_question}")
print(f"stacked_answers: {stacked_answers}")

difficulty = np.array([1, 2, 1, 3, 2, 2, 3])

result = np.vstack((stacked_question, stacked_answers, difficulty)).T
print(f"result: {result}")
print(f"result shape: {result.shape}")



['Q3' 'Q1' 'Q2' 'Q4' 'Q5']
['A' 'B' 'D' 'C' 'B']
stacked_question: ['Q3' 'Q1' 'Q2' 'Q4' 'Q5' 'Q6' 'Q7']
stacked_answers: ['A' 'B' 'D' 'C' 'B' 'A' 'D']
result: [['Q3' 'A' '1']
 ['Q1' 'B' '2']
 ['Q2' 'D' '1']
 ['Q4' 'C' '3']
 ['Q5' 'B' '2']
 ['Q6' 'A' '2']
 ['Q7' 'D' '3']]
result shape: (7, 3)


In [ ]:
#Q4
import numpy as np
camera_frames = np.random.rand(6,9)
# print(camera_frames)

camera_frames_flatten = camera_frames.reshape(6,-1)
print(f"camera_frames_flatten:\n {camera_frames_flatten}")


log = np.random.rand(6 , 4)
new_log = log.T

print(f"new_log shape:{new_log.shape}")

week_temps = np.arange(84).reshape(7 , 4 , 3)
print(f"week_temps:{week_temps.shape}")

week_temps_transpose = week_temps.T
print(f"week_temps_transpose: {week_temps_transpose.shape}")

In [ ]:
#Q5
import numpy as np
confidence = np.array([0.9, 0.4, 0.7, 0.95, 0.3])
confidence_T = confidence.reshape(5,1)
print(confidence_T)
print(confidence_T.shape)


single_command_output = np.array([[[0.1, 0.7, 0.2]]])
new_single_command_output = single_command_output.squeeze()
print(new_single_command_output.shape)

In [ ]:
#6
import numpy as np
power_readings = np.array([2.1, -0.5, 3.4, -1.1, 0, 5.6])

power_new=np.clip(power_readings,0,None)
power_new1 =np.where(power_readings<0 ,0,power_readings)

matrix=np.array([[-0.4, 1.2, 0.0], [2.1, -1.5, 0.3]])
relu_output=np.maximum(0,matrix)
relu_output1=np.where(matrix<0,0,matrix)
print (relu_output1)


In [ ]:
# Q7
import numpy as np
logits = np.array([
     [2.5, 0.3, 0.1],
    [0.2, 0.1, 3.5],
    [1.0, 1.2, 0.9]
])


logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=1, keepdims=True)
probabilities = logits_exp / sum_exp_Z

print(probabilities)
print("-" * 30)
logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=1)
probabilities = logits_exp / sum_exp_Z

print(probabilities)

print("-" * 30)
logits_exp = np.exp(logits)
sum_exp_Z = np.sum(logits_exp, axis=0,keepdims=True)
probabilities = logits_exp / sum_exp_Z

print(probabilities)

In [ ]:
# Q8
cart_prices = np.array([120, 45, 300, 15, 80])
discount_items = cart_prices[:2].copy()
print(discount_items)
discount_items[0] = 0
print(cart_prices)
