In [44]:
# Q1:

"""
rows: Every row represents a student.

columns: Every column represents a student's feature.
     First column: study_hours
     Second column: attendance_percent
     Third column: previous_score
     Forth column: final_score

X:

"""

import numpy as np

students = np.array([
  [2, 60, 45, 50],
  [5, 80, 70, 75],
  [1, 40, 35, 38],
  [8, 90, 88, 92],
  [4, 75, 60, 65],
  [7, 85, 80, 84],
  [3, 55, 50, 52],
  [6, 70, 72, 78]
])

print(f"dtype: {students.dtype}")
print(f"size: {students.size}")
print(f"shape: {students.shape}")
print(f"ndim: {students.ndim}")

X = students[:, :3]
print(f"X:\n{X}")

y = students[:, -1]
print(f"y:\n{y}")

print(f"X.shape:\n{X.shape}")
print(f"y.shape:\n{y.shape}")

dtype: int64
size: 32
shape: (8, 4)
ndim: 2
X:
[[ 2 60 45]
 [ 5 80 70]
 [ 1 40 35]
 [ 8 90 88]
 [ 4 75 60]
 [ 7 85 80]
 [ 3 55 50]
 [ 6 70 72]]
y:
[50 75 38 92 65 84 52 78]
X.shape:
(8, 3)
y.shape:
(8,)


In [45]:
## Q2:
rule_based_label = np.where(y > 60, 'pass', "fail")
mask = rule_based_label == "pass"
passed = np.sum(mask)
failed = len(rule_based_label) - passed

print(f"{passed} Student passed\n{failed} Student failed")

5 Student passed
3 Student failed


In [49]:
## Q3

# study_hours, attendance_percent, previous_score
mean_study_hours = np.mean(X[:, 0])
print(f"mean_study_hours: {mean_study_hours}")

min_attendance_percent = np.min(X[:, 1])
print(f"min_attendance_percent: {min_attendance_percent}")

max_attendance_percent = np.max(X[:, 1])
print(f"max_attendance_percent: {max_attendance_percent}")

study_hours = X[:, 0]
attendance_percent = X[:, 1]
effort_score = study_hours * attendance_percent / 100
print(f"effort_score: {effort_score}")
print(f"effort_score: {effort_score.shape}")
print(f"X:\n{X.shape}")
effort_score_new = effort_score.reshape(-1, 1)
print(f"effort_score:\n{effort_score_new.shape}")

# X_new = np.concatenate((X, effort_score_new), axis=1)
X_new_stack = np.hstack((X, effort_score_new))
print(f"X_new shape: {X_new_stack.shape}")

mean_study_hours: 4.5
min_attendance_percent: 40
max_attendance_percent: 90
effort_score: [1.2  4.   0.4  7.2  3.   5.95 1.65 4.2 ]
effort_score: (8,)
X:
(8, 3)
effort_score:
(8, 1)
X_new shape: (8, 4)


In [ ]:
## Q4
import numpy as np
students = np.array([
     [2, 60, 45, 50],
     [5, 80, 70, 75],
     [1, 40, 35, 38],
     [8, 90, 88, 92],
     [4, 75, 60, 65],
     [7, 85, 80, 84],
     [3, 55, 50, 52],
     [6, 70, 72, 78]
])
final_score = students[:,-1]
class_label = np.where(final_score >= 60, "pass","fail")
print(class_label)
mask = class_label == "pass"
passed=np.sum(mask)
failed = len(class_label) - passed
print(f"passed: {passed}")
print(f"failed: {failed}")

pass_percent = passed / len(class_label) * 100
print(pass_percent)

In [ ]:
# Q5:
print(f"final_score:{final_score}")
level_label = np.where(final_score < 60, "weak",
                       np.where((60 <= final_score) & (final_score < 80),"normal","strong"))

print(level_label)

weak = np.sum(level_label == "weak")
normal = np.sum(level_label == "normal")
strong = np.sum(level_label == "strong")
print(weak)

weak_sample = students[level_label == "weak"]
print(weak_sample)
mean_study_hours_weak = np.mean(weak_sample[:,0])
print(f"mean_study_hours_weak: {mean_study_hours_weak}")


normal_sample = students[level_label == "normal"]
print(normal_sample)
mean_study_hours_normal = np.mean(normal_sample[:,0])
print(f"mean_study_hours_normal: {mean_study_hours_normal}")


strong_sample = students[level_label == "strong"]
print(strong_sample)
mean_study_hours_strong = np.mean(strong_sample[:,0])
print(f"mean_study_hours_strong: {mean_study_hours_strong}")


# 3 کلاسه هست ==> multiclass classification

In [ ]:
##Q6
x = students

x_min = np.min(x, axis=0)
x_max = np.max(x, axis=0)
x_mean = np.mean(x, axis=0)
x_std = np.std(x, axis=0)

x_scaled = (x - x_min) / (x_max - x_min)
print(x_scaled)
print(np.min(x_scaled))
print(np.max(x_scaled))
