In [90]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
import pandas as pd
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
from sklearn.metrics import recall_score, make_scorer
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, KFold, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import recall_score, make_scorer


In [91]:
dict = {
    "temperature_c":
        [-0.6, 40.7, 17.7, 6.4, 20.0, 8.4, 35.5, -3.1, 0.1, 31.1, -2.6, 31.5, -4.6, 24.1, 33.5, 37.2, 41.3, 18.3, 11.6,
         35.8, 13.7,
         25.3, -4.0, 33.0, 15.2, 21.3, 31.6, 13.9, 37.7, 25.5, 29.2, 31.6, 11.5, -4.1, 11.9, 9.3, 38.2, 6.9, 6.3, 37.8,
         31.5, 15.2,
         38.3, 28.3, -1.6, 10.1, 34.7, 24.9, 23.9, 33.0, 24.9, 7.6, 13.1, 11.2, 4.4, 7.2, 26.6, 34.9, 4.5, 31.2, 34.1,
         20.3, 12.5,
         4.5, 3.8, 10.2, -1.6, 4.1, 38.2, 23.8, -3.2, 7.9, 29.0, 38.9, 13.7, 28.7, 33.3, -3.6, 33.9, 17.5, 8.2, 22.9,
         -2.0, 2.9, 20.1, 22.4, 5.6, 30.1, 31.0, 11.6, 23.0, 41.0, 8.6, 24.4, 10.0, 38.4, 16.8, 35.4, 3.6, 8.3, 8.2,
         22.1, 18.1, 30.5, -1.8, 38.6, 8.5, 20.8, 19.8, 18.1, 39.7, 23.7, 14.6, 15.6, 6.1, 41.1, 30.4, 8.7, 8.7, 29.0,
         18.7, -3.1,
         19.0, 12.7, 30.3, 28.8, -1.4, 35.4, -2.2, 26.0, -1.8, 27.9, 12.6, 4.6, 32.1, 41.1, 23.7, 17.6, 18.6, -2.4,
         -2.4, 6.5, 0.3, 13.7, 4.8, 21.9, 20.7, -2.8, 30.1, -4.9, 35.0, 23.5, 37.4, 4.0, 4.2, -0.5, 11.0, 22.2, -1.6,
         5.6, 16.8, 27.6, 18.5, 18.5, 13.7, -1.1, 25.1, 19.8, 6.0, 34.2,
         5.5, 37.8, 39.3, 17.9, 27.0, 32.9, 10.2, 7.2, -4.0, 5.2, 28.5, 40.8, 27.3, -3.1, 32.6, 6.8, 4.8, 4.8, 22.1,
         -0.3, -3.7, 10.4
            , 27.5, 3.3, 39.7, 24.3, -2.3, 10.2, 26.9, 1.1, 26.7, 24.1, 41.2, 28.2, 2.6, 18.5, 27.7, 5.8, 41.6, 7.1,
         1.2, 21.8, 23.9, 20.2, 21.8, 6.8, -0.8, 6.8, 16.9, 18.0, 17.4, 6.4, 38.3, 2.0, 11.8, 12.0, 17.0, 22.0, 15.2,
         24.5, 26.7, -4.0, 18.0, -1.7, 25.4, 32.0, 38.5, 12.8, 20.1, 29.2, 7.4, 21.8, 28.8, 3.3, 15.1, 21.7, 38.0, 26.0,
         10.6, 24.5, 26.7, 3.3, 17.7, 2.3, 40.5, 15.5, 35.6, 6.6, 29.2, 39.9],
    "household_size":
        [5, 1, 1, 3, 1, 1, 2, 1, 3, 2, 1, 3, 1, 4, 5, 4, 6, 4, 4, 1, 2, 5, 5, 4, 5, 2, 2, 6, 1, 1, 3, 1, 2, 4, 1, 1, 4,
         2, 2, 4, 2, 4, 4, 4, 2, 2, 3, 5, 1, 1, 1, 5, 4,
         5, 6, 3, 1, 5, 6, 6, 4, 5, 6, 3, 4, 1, 2, 4, 5, 3, 3, 3, 1, 6, 4, 2, 1, 1, 2, 6, 3, 1, 3, 3, 2, 6, 6, 6, 1, 3,
         4, 1, 1, 1, 6, 1, 2, 3, 3, 3, 1, 2, 3, 3, 2, 5,
         2, 1, 4, 6, 3, 5, 2, 6, 2, 6, 4, 5, 4, 3, 3, 6, 4, 5, 4, 1, 4, 4, 1, 2, 4, 3, 1, 3, 4, 4, 6, 5, 1, 2, 5, 3, 2,
         5, 3, 4, 6, 2, 5, 6, 3, 6, 4, 4, 3, 4, 5, 4, 1,
         2, 4, 3, 6, 3, 2, 6, 6, 5, 4, 3, 6, 5, 6, 6, 2, 6, 5, 1, 1, 4, 2, 6, 3, 4, 2, 5, 3, 1, 2, 5, 2, 3, 4, 2, 5, 2,
         1, 4, 6, 4, 5, 6, 4, 4, 2, 2, 1, 1, 3, 3, 2, 5,
         6, 1, 5, 3, 5, 3, 1, 3, 1, 1, 3, 4, 6, 3, 5, 1, 2, 6, 6, 4, 1, 6, 5, 4, 4, 3, 1, 1, 5, 5, 5, 6, 5, 4, 3, 4, 1,
         1, 4, 3, 5, 4, 2, 3, 3, 4, 6, 3],
    "ac_units":
        [0, 1, 2, 0, 1, 3, 2, 2, 0, 1, 0, 3, 1, 1, 3, 1, 1, 0, 3, 3, 1, 3, 1, 2, 2, 2, 1, 1, 3, 2, 0, 1, 0, 2, 1, 3, 2,
         0, 3, 3, 0, 0, 1, 3, 3, 2, 1, 1, 3, 1, 2, 2, 1,
         3, 0, 2, 2, 2, 3, 3, 1, 3, 3, 3, 1, 2, 1, 1, 0, 1, 3, 1, 2, 0, 2, 0, 2, 0, 1, 1, 3, 2, 3, 0, 2, 2, 2, 2, 0, 0,
         2, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 1, 3, 1, 0, 3,
         0, 3, 0, 2, 1, 1, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 2, 0, 3, 2, 0, 1, 3, 2, 3, 0, 3, 3, 1, 0, 0, 3, 1, 2, 3, 0, 3,
         1, 0, 0, 1, 1, 1, 1, 1, 3, 2, 2, 1, 3, 0, 3, 3,
         0, 1, 1, 2, 3, 0, 0, 2, 0, 3, 0, 1, 1, 0, 3, 1, 3, 0, 1, 0, 0, 3, 2, 3, 1, 2, 0, 1, 3, 1, 0, 0, 0, 3, 0, 2, 1,
         0, 1, 1, 3, 1, 3, 1, 3, 2, 3, 3, 1, 2, 1, 3, 3,
         1, 3, 1, 2, 1, 3, 1, 1, 1, 2, 3, 0, 2, 3, 3, 1, 3, 2, 1, 0, 0, 0, 2, 0, 1, 0, 3, 1, 1, 3, 3, 3, 1, 3, 2, 0, 0,
         3, 3, 3, 3, 3, 2, 0, 2, 0, 0, 1],
    "wiring_install_year":
        [2002, 1988, 2002, 1983, 1988, 1976, 1979, 1985, 2010, 1979, 1976, 2006, 1984, 2012, 2003, 2018, 1979, 2020,
         1987, 1996, 1975, 1994, 1984, 2006, 2019, 2004, 1976, 2023, 2006, 1985, 1987, 2001, 1979, 2016, 1997, 1981,
         1989, 2013, 1992, 1989, 1975, 2011, 1977, 2020, 2008, 2001, 2005, 1985, 2004, 1979, 1985, 1989, 1996, 1989,
         1978, 1993, 2003, 2018, 1989, 2015, 1998, 1983, 2009, 2005, 2023, 2002, 1982, 1989, 2006, 2006, 2016,
         1982, 1988, 2016, 1990, 2003, 2002, 2023, 2021, 2005, 1984, 1997, 1982, 1996, 1975, 2019, 2015, 1996, 1981,
         1976, 1999, 2005, 2005, 2017, 2013, 2012, 1996, 2012, 2002, 2012, 1975, 1995, 1989, 2012, 2006, 1984, 1988,
         1988, 2005, 1988, 2012, 1989, 1980, 1990, 2011, 1977, 2018, 1989, 2000, 1982, 1975, 2002, 2013, 1979, 2011,
         2017, 1987, 2007, 1998, 1987, 1984, 1993, 1979, 1983, 1994, 2021, 2004, 1995, 2002, 1995, 1982, 2009,
         1992, 1991, 2003, 1989, 1977, 2003, 1999, 1986, 2014, 2022, 1985, 1984, 2023, 1987, 1989, 1981, 2012, 1992,
         2000, 2003, 2010, 2009, 2000, 1995, 2019, 2011, 2020, 2003, 1980, 2020, 1981, 2004, 2016, 2012, 2005, 2000,
         2011, 2016, 2022, 2023, 2003, 2001, 1977, 1979, 2001, 2005, 1997, 1988, 2018, 2019, 1996, 1979, 1976, 1986,
         2019, 2018, 2020, 1995, 1999, 1992, 1998, 1975, 1992, 2012, 1986, 2002, 2018, 2006, 1991, 1984, 1975,
         1982, 1990, 1988, 2003, 1999, 1982, 1984, 2015, 2023, 2007, 2006, 1997, 2004, 1980, 2023, 2004, 1986, 1989,
         1991, 1987, 1985, 2001, 2007, 1976, 2000, 1976, 1997, 1983, 2019, 1989, 2017, 2013, 2001, 2018, 2006, 1985,
         1986, 2007, 1995, 1996, 2014, 1998, 2020, 1997, 1981, 1994, 2016],
    "outage_risk":
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
         0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
         0]
}
# list_dict = dict.keys()
# for name in list_dict:
#     print(len(dict[name]))
dict['outage_risk'] = dict['outage_risk'][:260]
smart_home_data = pd.DataFrame.from_dict(dict)

In [92]:
X = smart_home_data.iloc[:, :-1]
y = smart_home_data.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
y_pred = [0] * len(y_test)
print(y_pred)
print(f"report: \n{classification_report(y_test, y_pred, zero_division=0)}")
print(confusion_matrix(y_test, y_pred))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        48
           1       0.00      0.00      0.00         4

    accuracy                           0.92        52
   macro avg       0.46      0.50      0.48        52
weighted avg       0.85      0.92      0.89        52

[[48  0]
 [ 4  0]]


In [93]:
for depth in [None, 4]:
    if depth is None:
        model = DecisionTreeClassifier(random_state=42)
    else:
        model = RandomForestClassifier(random_state=42, max_depth=depth)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, zero_division=0)
    print(report)
    print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89        48
           1       0.00      0.00      0.00         4

    accuracy                           0.81        52
   macro avg       0.46      0.44      0.45        52
weighted avg       0.84      0.81      0.82        52

[[42  6]
 [ 4  0]]
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        48
           1       0.00      0.00      0.00         4

    accuracy                           0.92        52
   macro avg       0.46      0.50      0.48        52
weighted avg       0.85      0.92      0.89        52

[[48  0]
 [ 4  0]]


In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
for depth in [None, 4]:
    if depth is None:
        model = DecisionTreeClassifier(random_state=42)
    else:
        model = RandomForestClassifier(random_state=42, max_depth=depth)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, zero_division=0)
    print(report)
    print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93        47
           1       0.00      0.00      0.00         5

    accuracy                           0.87        52
   macro avg       0.45      0.48      0.46        52
weighted avg       0.81      0.87      0.84        52

[[45  2]
 [ 5  0]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        47
           1       0.00      0.00      0.00         5

    accuracy                           0.90        52
   macro avg       0.45      0.50      0.47        52
weighted avg       0.82      0.90      0.86        52

[[47  0]
 [ 5  0]]


In [95]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
recall_scorer = make_scorer(recall_score)

# StratifiedKFold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# مدل
model = DecisionTreeClassifier(max_depth=4, random_state=42)

# انجام Cross-Validation
skf_scores = cross_val_score(model, X_scaled, y, cv=skf, scoring=recall_scorer)

print(f"\nنمرات Recall در 5 Fold: {skf_scores}")
print(f"میانگین Recall: {skf_scores.mean():.4f}")
print(f"انحراف معیار: {skf_scores.std():.4f}")

# نمایش نسبت کلاس 1 در هر Fold
print("\nنسبت کلاس 1 در هر Fold (Stratified):")
for fold, (train_idx, test_idx) in enumerate(skf.split(X_scaled, y)):
    y_test_fold = y.iloc[test_idx]
    ratio = sum(y_test_fold == 1) / len(y_test_fold)
    print(f"  Fold {fold+1}: {ratio:.4f} ({sum(y_test_fold==1)}/{len(y_test_fold)})")

# ============================================
# 4. بخش د - قسمت 2: KFold معمولی (بدون Stratify)
# ============================================
print("\n" + "="*60)
print("قسمت 2: KFold معمولی (بدون Stratify)")
print("="*60)

# KFold معمولی
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# انجام Cross-Validation
kf_scores = cross_val_score(model, X_scaled, y, cv=kf, scoring=recall_scorer)

print(f"\nنمرات Recall در 5 Fold: {kf_scores}")
print(f"میانگین Recall: {kf_scores.mean():.4f}")
print(f"انحراف معیار: {kf_scores.std():.4f}")

# نمایش نسبت کلاس 1 در هر Fold
print("\nنسبت کلاس 1 در هر Fold (KFold معمولی):")
for fold, (train_idx, test_idx) in enumerate(kf.split(X_scaled)):
    y_test_fold = y.iloc[test_idx]
    ratio = sum(y_test_fold == 1) / len(y_test_fold)
    print(f"  Fold {fold+1}: {ratio:.4f} ({sum(y_test_fold==1)}/{len(y_test_fold)})")

# ============================================
# 5. بخش د - قسمت 3: Reason (تحلیل و مقایسه)
# ============================================
print("\n" + "="*60)
print("قسمت 3: Reason - مقایسه دو روش")
print("="*60)

print("""
📊 مقایسه Stratified K-Fold با KFold معمولی:

1. Stratified K-Fold:
   - نسبت کلاس 1 در همه Folds تقریباً برابر است
   - هر Fold نماینده خوبی از کل داده است
   - برای داده‌های نامتوازن ایمن‌تر است

2. KFold معمولی:
   - نسبت کلاس 1 در Folds می‌تواند بسیار متفاوت باشد
   - ممکن است یک Fold هیچ نمونه کلاس 1 نداشته باشد
   - در این صورت Recall در آن Fold تعریف‌نشده یا صفر می‌شود

⚠️ خطر KFold معمولی در داده‌های نامتوازن:
اگر یک Fold به طور تصادفی هیچ نمونه از کلاس 1 نداشته باشد:
- Recall = 0/0 → تعریف نشده (undefined)
- یا اگر حداقل یک نمونه داشته باشد اما مدل آن را تشخیص ندهد: Recall = 0
- این باعث می‌شود میانگین Recall پایین بیاید و ارزیابی غیرواقعی شود
""")

# ============================================
# 6. نمایش نتایج در جدول (مطابق PDF)
# ============================================
results_df = pd.DataFrame({
    'Method': ['StratifiedKFold', 'KFold (Normal)'],
    'Mean Recall': [skf_scores.mean(), kf_scores.mean()],
    'Std Recall': [skf_scores.std(), kf_scores.std()],
    'Min Recall': [skf_scores.min(), kf_scores.min()],
    'Max Recall': [skf_scores.max(), kf_scores.max()]
})

print("\n" + "="*60)
print("جدول مقایسه نتایج:")
print("="*60)
print(results_df.to_string(index=False))

# ============================================
# 7. بررسی Foldهای خاص
# ============================================
print("\n" + "="*60)
print("بررسی Foldهایی با نسبت کلاس 1 کم:")
print("="*60)

# پیدا کردن Fold با کمترین نسبت کلاس 1 در KFold معمولی
min_ratio = 1.0
min_fold = -1
for fold, (train_idx, test_idx) in enumerate(kf.split(X_scaled)):
    y_test_fold = y.iloc[test_idx]
    ratio = sum(y_test_fold == 1) / len(y_test_fold)
    if ratio < min_ratio:
        min_ratio = ratio
        min_fold = fold + 1

print(f"\n🔴 Fold با کمترین نسبت کلاس 1 در KFold معمولی: Fold {min_fold}")
print(f"   نسبت کلاس 1: {min_ratio:.4f}")
print(f"   تعداد نمونه‌های کلاس 1 در این Fold: {sum(y.iloc[test_idx]==1)}")
print(f"   تعداد کل نمونه‌ها در این Fold: {len(y.iloc[test_idx])}")

# محاسبه Recall برای این Fold خاص
model.fit(X_scaled[train_idx], y.iloc[train_idx])
y_pred = model.predict(X_scaled[test_idx])
recall_fold = recall_score(y.iloc[test_idx], y_pred)
print(f"   Recall در این Fold: {recall_fold:.4f}")


نمرات Recall در 5 Fold: [0. 0. 0. 0. 0.]
میانگین Recall: 0.0000
انحراف معیار: 0.0000

نسبت کلاس 1 در هر Fold (Stratified):
  Fold 1: 0.0769 (4/52)
  Fold 2: 0.0769 (4/52)
  Fold 3: 0.0769 (4/52)
  Fold 4: 0.0962 (5/52)
  Fold 5: 0.0962 (5/52)

قسمت 2: KFold معمولی (بدون Stratify)

نمرات Recall در 5 Fold: [0. 0. 0. 0. 0.]
میانگین Recall: 0.0000
انحراف معیار: 0.0000

نسبت کلاس 1 در هر Fold (KFold معمولی):
  Fold 1: 0.0962 (5/52)
  Fold 2: 0.0577 (3/52)
  Fold 3: 0.1154 (6/52)
  Fold 4: 0.0962 (5/52)
  Fold 5: 0.0577 (3/52)

قسمت 3: Reason - مقایسه دو روش

📊 مقایسه Stratified K-Fold با KFold معمولی:

1. Stratified K-Fold:
   - نسبت کلاس 1 در همه Folds تقریباً برابر است
   - هر Fold نماینده خوبی از کل داده است
   - برای داده‌های نامتوازن ایمن‌تر است

2. KFold معمولی:
   - نسبت کلاس 1 در Folds می‌تواند بسیار متفاوت باشد
   - ممکن است یک Fold هیچ نمونه کلاس 1 نداشته باشد
   - در این صورت Recall در آن Fold تعریف‌نشده یا صفر می‌شود

⚠️ خطر KFold معمولی در داده‌های نامتوازن:
اگر یک Fold به طور